/**
 * @file    test_can_driver.h
 * @brief   CAN 驱动测试头文件
 * @author  Generated by AI Assistant
 * @date    2025-12-06
 */

#ifndef __TEST_CAN_DRIVER_H
#define __TEST_CAN_DRIVER_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include <stdint.h>

/* Exported functions prototypes ---------------------------------------------*/

/**
 * @brief   运行所有 CAN 驱动测试
 * @note    该函数会执行完整的测试套件，包括：
 *          - 初始化测试
 *          - 过滤器配置测试
 *          - 环回收发测试
 *          - 状态查询测试
 *          - 边界条件测试
 *
 * @retval  0: 所有测试通过
 *          -1: 有测试失败
 *
 * @usage   在 main.c 中调用：
 *          @code
 *          #include "test_can_driver.h"
 *
 *          int main(void) {
 *              // ... 初始化代码 ...
 *
 *              // 运行 CAN 驱动测试
 *              int result = can_driver_run_tests();
 *              if (result == 0) {
 *                  printf("All tests passed!\r\n");
 *              } else {
 *                  printf("Some tests failed!\r\n");
 *              }
 *
 *              while (1) {}
 *          }
 *          @endcode
 */
int can_driver_run_tests(void);

/**
 * @brief   运行 CAN 环回自检（简化版）
 * @note    快速验证 CAN 驱动基本功能，适合在生产测试或系统启动时使用
 *          测试内容：
 *          1. 初始化为环回模式
 *          2. 配置过滤器
 *          3. 发送测试数据
 *          4. 接收并验证数据
 *
 * @retval  0: 自检通过
 *          -1: 自检失败
 *
 * @usage   @code
 *          if (can_driver_self_test() == 0) {
 *              printf("CAN self-test passed\r\n");
 *          }
 *          @endcode
 */
int can_driver_self_test(void);

#ifdef __cplusplus
}
#endif

#endif /* __TEST_CAN_DRIVER_H */
